name: 'osha_analytics'
version: '1.0.0'
config-version: 2

profile: 'osha_analytics'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  osha_analytics:
    staging:
      +schema: STAGING
      +materialized: view
    intermediate:
      +schema: INTERMEDIATE
      +materialized: view
    marts:
      +schema: MARTS
      +materialized: table