osha_analytics:
  outputs:
    dev:
      account: YKLSJPM-MBC31396
      database: OSHA_DB
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: STAGING
      threads: 4
      type: snowflake
      user: MUHAMMADMUNAWWAR
      warehouse: OSHA_WH
  target: dev
